### PR TITLE
docs(core): :memo: update docomentation of CoreListItemIcon

### PR DESCRIPTION
**Pull request by arkaprota**
## Description
the proper docomentation of CoreListItemIcon has been updated

**Image**

Screenshot 2024-08-17 120616

Ref: #193

### CODE REVIEW

**Comment by wrappidcare** [comment]
Merging since stale over 24hrs.

**Comment by arkaprota** [comment]
please check if there is any changes needed or not
@techoneel

**Comment by wrappidcare** [comment]
Merging since stale over 24hrs.

**Review by techoneel — APPROVED** [review]
Good to go

**Pull request merged**
