### PR TITLE
fix(core): :bug: the docomentation is not present has been updated

### PR DESCRIPTION
**Pull request by arkaprota**
## Description

-the docomentation was not present has been updated
-it was showing not working - by using the sample code the user can understand how it works

**Image**

Screenshot 2024-08-16 171656

Ref: #189

### CODE REVIEW

**Comment by wrappidcare** [comment]
Merging since stale over 24hrs.

**Comment by arkaprota** [comment]
please check if there is any changes needed or not
@techoneel

**Comment by wrappidcare** [comment]
Merging since stale over 24hrs.

**Review by techoneel — APPROVED** [review]
Good to go

**Pull request merged**
