### PR TITLE
docs(global): 📝 update CoreLinearProgress documentation

### PR DESCRIPTION
**Pull request by PritamBag**
## Description
I updated the documentation of CoreLinearProgress, where I also give an example of how we can show a label with LinearProgress by passing a prop(showLabel), if this prop is passed then a label is displayed along with the LinearProgressbar. 
Ref: https://github.com/wrappid/guide-module/issues/231

## Related Issues

https://github.com/wrappid/native-web/issues/114 and https://github.com/wrappid/core/issues/332 need to be resolved before marge this.

## Checklist

- [X] I have performed a thorough self-review of my code.
- [X] I have added or updated relevant tests for my changes.
- [X] My code follows the project's style guidelines and best practices.
- [X] I have updated the documentation if necessary.
- [ ] I have added or updated relevant comments in my code.
- [ ] I have resolved any merge conflicts in my branch.

## Testing
I write code and pass all valid props in the code of this(CoreLinearProgress.docs.js) file, and the code works properly.

## Maintainer Notes

- [ ] Has this change been tested in a staging environment?
- [ ] Does this change introduce any breaking changes or deprecations?

### CODE REVIEW

**Comment by techoneel** [comment]
@anantakumarghosh please guide him with the pr template what to do and what not

**Comment by anantakumarghosh** [comment]
> @anantakumarghosh please guide him with the pr template what to do and what not

Sure.

**Review by techoneel — CHANGES_REQUESTED** [review]
update the pr description as per template

**Review by techoneel — APPROVED** [review]
good to go

**Pull request merged**
