### PR TITLE
docs: :memo: The completion of improvement of documentation  of CoreList

### PR DESCRIPTION
**Pull request by arkaprota**
## Description

There are documentation has been enhanced and new information has also added. Like  List_Item and the introduction part.

Ref: #163

**Image**

Screenshot 2024-08-12 175356

### CODE REVIEW

**Comment by techoneel** [comment]
Please check the linting issues and ask for review.

**Comment by anantakumarghosh** [comment]
Please fix lint errors @arkaprota

**Comment by arkaprota** [comment]
the eslint error has fixed please let me know if there is any changes needed or not
@techoneel

**Comment by wrappidcare** [comment]
Merging since stale over 24hrs.

**Pull request merged**
